### ISSUE TITLE
Invoking "make -j4 -l4" failed

### ISSUE THREAD

**Issue by musabahmed97** [BrunoEduardoCSantos/Pick-and-Place#2]
Everything works fine
But when I reach as **"Build The Project"** section and run the commands

$ cd ~/catkin_ws
$ catkin_make

It goes till 83 % which reads like this 
Building CXX object Pick-and-Place/kuka_arm/CMakeFiles/trajectory_sampler.dir/src/trajectory_sampler.cpp.o

but then Error appears

/home/fyp/catkin_ws/src/Pick-and-Place/kuka_arm/src/trajectory_sampler.cpp: In constructor ‘TrajectorySampler::TrajectorySampler(ros::NodeHandle)’:
/home/fyp/catkin_ws/src/Pick-and-Place/kuka_arm/src/trajectory_sampler.cpp:180:43: error: cannot convert ‘moveit::planning_interface::MoveItErrorCode’ to ‘bool’ in initialization
     bool success = move_group.plan(my_plan);
  
and so on till the last one which says

### **Invoking "make -j4 -l4" failed**

ANy help ?

**Comment by brunoeducsantos** [comment]
Hi,
I push a change that solves the issue.
Can you try it now?
Cheers,
Bruno

**Comment by musabahmed97** [comment]
I appreciate your effort mate but that change doesn't seem to work.

The error persists !

![Screenshot from 2019-03-31 21-03-12](https://user-images.githubusercontent.com/48132979/55291519-b4b0ef00-53f8-11e9-85e3-1a477e81dac0.png)

**Comment by brunoeducsantos** [comment]
For me it works fine. Try to make clean inside build folder. It might help.

**Comment by musabahmed97** [comment]
I deleted the workspace tried everything from the beginning i.e from making the Catkin Workspace

But still, out of luck !!!

Do you think I might be missing something ?

**Comment by brunoeducsantos** [comment]
Did you proceed according to the following steps?
```
 cd ~/catkin_ws
$ rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
$ cd ~/catkin_ws/src/Pick-and-Place/kuka_arm/scripts
$ sudo chmod +x target_spawn.py
$ sudo chmod +x IK_server.py
$ sudo chmod +x safe_spawner.s
```

**Comment by musabahmed97** [comment]
Yes sir, doing exactly step by step … !!!

**Comment by musabahmed97** [comment]
One more thing, can I ask you for a favor ???
 
I need a 6DOF, can you help ?
